### ISSUE TITLE
Travis CI build using mixed of 'local clone' and 'whatever is on master' b/c of gopkg.in

### ISSUE THREAD

**Issue by fasterthanlime** [kothar/brotli-go#17]
If you look carefully at travis' log output (comments mine);

```sh
# make canonical import directory (or so travis's go setup thinks)
$ mkdir -p $HOME/gopath/src/github.com/kothar/brotli-go

# copy everything from original build dir to there
$ rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/kothar/brotli-go/

# set `TRAVIS_BUILD_DIR` environment variable to our canonical import path
$ export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/kothar/brotli-go

# cd there
$ cd $HOME/gopath/src/github.com/kothar/brotli-go
```

It thinks `github.com/kothar/brotli-go` is the canonical import path, whereas `gopkg.in/kothar/brotli-go.v0` is.

This means, for example, that when running a travis build of a branch (for a pending pull request), the test files are those of the branch, but the `enc`, `dec`, `shared` modules are those of whatever is on master (because it fetches `gopkg.in/kothar/brotli-go.v0` separately)

I'll submit a PR to fix this, but we'll have to be careful once v1 comes around (I can think of something based on `$TRAVIS_TAG` to support v1+ but it won't be pretty)

**Comment by kothar** [comment]
How about just creating a link?:

~~~
mkdir -p $HOME/gopath/src/gopkg.in/kothar
ln -s ${TRAVIS_BUILD_DIR} $HOME/gopath/src/gopkg.in/kothar/brotli-go.v0
~~~

**Comment by fasterthanlime** [comment]
@kothar if that works too, cool! after that incident I'm a bit paranoid though and:

  * I don't feel good about having two copies of the source in the tree
  * I have no idea how go deals with symbolic links (as far as it's concerned, `github.com/kothar/brotli-go/enc/encode_test.go` and `gopkg.in/kothar/brotli-go.v0/enc/encode_test.go` are two different tests)

#18 is ugly because it copies+removes but the `mv` approach failed (don't know why) and that's the one they use for go projects on travis in the first place (don't know why either) — at least it tests pull requests reliably and that's all I'm personally asking for atm! :shipit:
