### ISSUE TITLE
cannot use p.c (type C.struct_CBrotliParams) as type C.CBrotliParams in function argument

### ISSUE THREAD

**Issue by emmauss** [kothar/brotli-go#38]
i get this error when compiling on ubuntu 14.04.1 ; using  go get github.com/kothar/brotli-go
here is the error;
`go/src/gopkg.in/kothar/brotli-go.v0/enc/encode.go:148: cannot use p.c (type C.struct_CBrotliParams) as type C.CBrotliParams in function argument
go/src/gopkg.in/kothar/brotli-go.v0/enc/encode.go:170: cannot use params.c (type C.struct_CBrotliParams) as type C.CBrotliParams in function argument
go/src/gopkg.in/kothar/brotli-go.v0/enc/encode.go:188: cannot use params.c (type C.struct_CBrotliParams) as type C.CBrotliParams in function argument`
i have installed build-essentials and gcc. i also get this error on any other go project that uses brotli, like
https://github.com/barnacs/compy

**Comment by fasterthanlime** [comment]
> ubuntu 14.04.1

Released on April 17, 2014? I'm fairly sure that if it ships a version of go, it must be severely outdated.

Try with go 1.6 or higher.

**Comment by kothar** [comment]
Hi @emmauss, hopefully you got everything working with a later version of Go, feel free to reopen this ticket if there are still issues!
